#!/usr/bin/env bash
# v0.30 R108: Bash 版本的 Android release keystore 生成器 (Mac/Linux dev)
#
# 背景 (R72 + R108):
# - R72 写了 PowerShell 版本 (`scripts/generate_release_keystore.ps1`) 给 Windows dev
# - R108 加这个 bash 版本给 Mac/Linux dev (CI / DevOps 必备)
# - R72 PowerShell 跟本脚本功能完全一致, 选一个跑就行
#
# 用法 (Bash, Mac / Linux):
#   chmod +x scripts/generate_android_keystore.sh
#   ./scripts/generate_android_keystore.sh
#   (交互式提示输入 storePassword / keyPassword / alias / dname)
#
# 非交互用法 (CI):
#   STORE_PASSWORD=xxx KEY_PASSWORD=yyy \
#     ALIAS=chroniccare VALIDITY=10000 KEYSIZE=2048 \
#     ./scripts/generate_android_keystore.sh
#
# 输出:
#   android/app/chroniccare-release.jks (binary, .gitignore 排除)
#   android/key.properties (text, .gitignore 排除)
#   $HOME/.chroniccare-keystore-backup/ 密码保护 ZIP
#
# 前置:
#   1. 装 Java JDK 17+ (keytool 命令行)
#   2. .gitignore 已排除 *.jks + key.properties (R67 已加)
#   3. 备份到 1Password / Bitwarden (丢 keystore = App 永久无法升级)
#
# ⚠️  本脚本会创建真实 keystore, 实际跑需 macOS / Linux + JDK 17+
#    详见 docs/audit/2026-08-10-cleanup/R108-android-keystore-setup.md

set -euo pipefail

# 路径 (兼容脚本所在位置)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
KEYSTORE_DIR="$PROJECT_ROOT/android/app"
KEYSTORE_PATH="$KEYSTORE_DIR/chroniccare-release.jks"
KEY_PROPS_PATH="$PROJECT_ROOT/android/key.properties"

# 1. 检查 keytool
if ! command -v keytool >/dev/null 2>&1; then
  echo "[FAIL] keytool 找不到。请装 Java JDK 17+ 并配 PATH。" >&2
  echo "       Mac:   brew install openjdk@17 && export PATH=\$(brew --prefix openjdk@17)/bin:\$PATH" >&2
  echo "       Linux: sudo apt install openjdk-17-jdk   (Debian/Ubuntu)" >&2
  echo "              sudo yum install java-17-openjdk  (RHEL/CentOS)" >&2
  exit 1
fi

# 2. 检查 keystore 已存在
if [ -f "$KEYSTORE_PATH" ]; then
  echo "[WARN] $KEYSTORE_PATH 已存在, 不覆盖 (避免误删已签 AAB 的 keystore)" >&2
  echo "       如确认要重新生成, 请手动删除后重跑。" >&2
  exit 0
fi

# 3. 参数 (交互式 OR 环境变量)
echo ""
echo "================================================"
echo "  Android Release Keystore 生成向导 (R108 bash)"
echo "================================================"
echo ""

# validity (天) — Play Console 建议 25+ 年 = 9125+ 天; 用 10000 = ~27 年
VALIDITY="${VALIDITY:-}"
if [ -z "$VALIDITY" ]; then
  read -r -p "有效天数 (默认 10000 = ~27 年, R68 PLAYSTORE_SIGNING_GUIDE 推荐): " VALIDITY
  VALIDITY="${VALIDITY:-10000}"
fi

# keysize — RSA 2048 是行业标准, 4096 是 overkill 但更稳
KEYSIZE="${KEYSIZE:-}"
if [ -z "$KEYSIZE" ]; then
  read -r -p "RSA keysize (默认 2048): " KEYSIZE
  KEYSIZE="${KEYSIZE:-2048}"
fi

# alias
ALIAS="${ALIAS:-}"
if [ -z "$ALIAS" ]; then
  read -r -p "key alias (默认 chroniccare): " ALIAS
  ALIAS="${ALIAS:-chroniccare}"
fi

# DName
DName="${DName:-}"
if [ -z "$DName" ]; then
  read -r -p "Distinguished Name (默认 'CN=ChronicCare, OU=App, O=ChronicCare, L=Beijing, ST=Beijing, C=CN'): " DName
  DName="${DName:-CN=ChronicCare, OU=App, O=ChronicCare, L=Beijing, ST=Beijing, C=CN}"
fi

# storePassword
STORE_PASSWORD="${STORE_PASSWORD:-}"
if [ -z "$STORE_PASSWORD" ]; then
  # 提示输入 + 确认 (不用 -s 因为有些 shell 不支持, 用 stty 关闭 echo)
  echo "storePassword (keystore 主密码, 强密码, 8+ 字符):"
  stty -echo
  read -r STORE_PASSWORD
  stty echo
  echo "storePassword (再次输入确认):"
  stty -echo
  read -r STORE_PASSWORD_CONFIRM
  stty echo
  echo ""
  if [ "$STORE_PASSWORD" != "$STORE_PASSWORD_CONFIRM" ]; then
    echo "[FAIL] storePassword 两次输入不一致" >&2
    exit 1
  fi
fi

# keyPassword
KEY_PASSWORD="${KEY_PASSWORD:-}"
if [ -z "$KEY_PASSWORD" ]; then
  echo "keyPassword (key 密码, 跟 storePassword 同 OK):"
  stty -echo
  read -r KEY_PASSWORD
  stty echo
  echo "keyPassword (再次输入确认):"
  stty -echo
  read -r KEY_PASSWORD_CONFIRM
  stty echo
  echo ""
  if [ "$KEY_PASSWORD" != "$KEY_PASSWORD_CONFIRM" ]; then
    echo "[FAIL] keyPassword 两次输入不一致" >&2
    exit 1
  fi
fi

# 4. 生成 keystore
echo "[1/3] 生成 keystore (R108 keytool 自动化)..."
echo "      路径: $KEYSTORE_PATH"
echo "      alias: $ALIAS"
echo "      validity: $VALIDITY days"
echo "      keysize: $KEYSIZE bits"
echo ""

JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF-8" keytool -genkeypair \
  -keystore "$KEYSTORE_PATH" \
  -alias "$ALIAS" \
  -keyalg RSA \
  -keysize "$KEYSIZE" \
  -validity "$VALIDITY" \
  -storepass "$STORE_PASSWORD" \
  -keypass "$KEY_PASSWORD" \
  -dname "$DName"

echo ""
echo "[2/3] 写 key.properties..."

# 5. 写 key.properties (相对路径: keystore 跟 key.properties 同 android/ 目录)
cat > "$KEY_PROPS_PATH" <<EOF
# Generated by scripts/generate_android_keystore.sh (R108)
# 安全: 本文件含密码, .gitignore 已排除, 不要 commit
# 备份密码到 1Password / Bitwarden, 丢 keystore = App 永久无法升级
storeFile=app/chroniccare-release.jks
storePassword=$STORE_PASSWORD
keyAlias=$ALIAS
keyPassword=$KEY_PASSWORD
EOF

# 6. 备份到 $HOME (Mac/Linux 各自)
echo ""
echo "[3/3] 备份 keystore + key.properties..."
BACKUP_DIR="$HOME/.chroniccare-keystore-backup"
mkdir -p "$BACKUP_DIR"
DATE=$(date +%Y%m%d-%H%M%S)
BACKUP_JKS="$BACKUP_DIR/chroniccare-release-$DATE.jks"
BACKUP_PROPS="$BACKUP_DIR/key-properties-$DATE.txt"
cp "$KEYSTORE_PATH" "$BACKUP_JKS"
cp "$KEY_PROPS_PATH" "$BACKUP_PROPS"
echo "      备份到:"
echo "        $BACKUP_JKS"
echo "        $BACKUP_PROPS"

echo ""
echo "[OK] keystore 生成完成!"
echo ""
echo "下一步:"
echo "  1. 跑 'flutter build appbundle --release' 验证签名"
echo "  2. 检查 'aapt dump badging build/app/outputs/bundle/release/app-release.aab | grep package' 确认 keystore"
echo "  3. Play Console → App integrity → Enable Play App Signing + 上传 .aab"
echo "  4. 备份到 1Password / Bitwarden (强烈推荐, 丢 keystore = App 永久无法升级)"
echo ""
