#!/usr/bin/env pwsh
<#
v0.27 R72: 自动生成 Android release keystore (上架 P0 阻塞脚本化)

背景:
- R70 修了 build.gradle.kts signingConfig 切 release (R70 commit 5592f96 留 TODO)
- R68 appstore/googleplay 报告 P0: 真实 keystore 是上架硬阻塞
- 之前 user 必须手动跑 keytool, R72 脚本化避免漏 keysize / validity 参数

用法 (PowerShell):
  .\scripts\generate_release_keystore.ps1
  (交互式提示输入 storePassword / keyPassword / 各种名称)

输出:
  android/app/chroniccare-release.jks (binary, NOT committed, .gitignore 排除)
  android/key.properties (text, NOT committed, .gitignore 排除)
  + 备份到 $HOME/.chroniccare-keystore-backup/ (密码保护 ZIP)

前置:
  1. 装 Java JDK 17+ (keytool 命令行工具)
  2. .gitignore 已排除 *.jks + key.properties (R67 已加)
  3. 备份到 1Password / Bitwarden (丢 keystore = App 永久无法升级)
#>

$ErrorActionPreference = 'Stop'

# 1. 路径
$keystorePath = Join-Path $PSScriptRoot '..\android\app\chroniccare-release.jks'
$keyPropsPath = Join-Path $PSScriptRoot '..\android\key.properties'
$keystorePath = (Resolve-Path $keystorePath).Path
$keyPropsPath = (Resolve-Path $keyPropsPath).Path

# 2. 检查 keytool 可用
try {
    $keytoolVersion = & keytool -help 2>&1 | Select-String -Pattern "keytool" | Select-Object -First 1
} catch {
    Write-Host "[FAIL] keytool 找不到。请装 Java JDK 17+ 并配 PATH。" -ForegroundColor Red
    exit 1
}

# 3. 检查 keystore 已存在
if (Test-Path $keystorePath) {
    Write-Host "[WARN] $keystorePath 已存在, 不覆盖 (避免误删已签 AAB 的 keystore)" -ForegroundColor Yellow
    Write-Host "       如确认要重新生成, 请手动删除后重跑。"
    exit 0
}

# 4. 交互式输入
Write-Host ""
Write-Host "================================================" -ForegroundColor Cyan
Write-Host "  Android Release Keystore 生成向导 (R72)"
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""

$validity = Read-Host "有效天数 (默认 10000 = ~27 年, R68 PLAYSTORE_SIGNING_GUIDE.md 推荐)"
if ([string]::IsNullOrWhiteSpace($validity)) { $validity = "10000" }

$keysize = Read-Host "RSA keysize (默认 2048, 256 是 overkill 但更稳)"
if ([string]::IsNullOrWhiteSpace($keysize)) { $keysize = "2048" }

$alias = Read-Host "key alias (默认 chroniccare)"
if ([string]::IsNullOrWhiteSpace($alias)) { $alias = "chroniccare" }

$dname = Read-Host "Distinguished Name (DName, 默认 'CN=ChronicCare, OU=App, O=ChronicCare, L=Beijing, ST=Beijing, C=CN')"
if ([string]::IsNullOrWhiteSpace($dname)) {
    $dname = "CN=ChronicCare, OU=App, O=ChronicCare, L=Beijing, ST=Beijing, C=CN"
}

$storePassword = Read-Host "storePassword (keystore 主密码, 强密码, 8+ 字符)"
$storePasswordSecure = Read-Host -AsSecureString "storePassword (再次输入确认)"
$storePasswordConfirm = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($storePasswordSecure)
)
if ($storePassword -ne $storePasswordConfirm) {
    Write-Host "[FAIL] storePassword 两次输入不一致" -ForegroundColor Red
    exit 1
}

$keyPassword = Read-Host "keyPassword (key 密码, 跟 storePassword 同 OK)"
$keyPasswordSecure = Read-Host -AsSecureString "keyPassword (再次输入确认)"
$keyPasswordConfirm = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($keyPasswordSecure)
)
if ($keyPassword -ne $keyPasswordConfirm) {
    Write-Host "[FAIL] keyPassword 两次输入不一致" -ForegroundColor Red
    exit 1
}

# 5. 生成 keystore
Write-Host ""
Write-Host "[1/3] 生成 keystore (R72 keytool 自动化)..." -ForegroundColor Green
Write-Host "      路径: $keystorePath"
Write-Host "      alias: $alias"
Write-Host "      validity: $validity days"
Write-Host "      keysize: $keysize bits"
Write-Host ""

$env:JAVA_TOOL_OPTIONS = "-Dfile.encoding=UTF-8"
& keytool -genkeypair `
    -keystore $keystorePath `
    -alias $alias `
    -keyalg RSA `
    -keysize $keysize `
    -validity $validity `
    -storepass $storePassword `
    -keypass $keyPassword `
    -dname $dname

if ($LASTEXITCODE -ne 0) {
    Write-Host "[FAIL] keytool 生成失败 (exit $LASTEXITCODE)" -ForegroundColor Red
    exit 1
}

# 6. 写 key.properties
Write-Host ""
Write-Host "[2/3] 写 key.properties..." -ForegroundColor Green

$propsContent = @"
# Generated by scripts/generate_release_keystore.ps1 (R72)
# 安全: 本文件含密码, .gitignore 已排除, 不要 commit
# 备份密码到 1Password / Bitwarden, 丢 keystore = App 永久无法升级
storeFile=$($keystorePath | Split-Path -Leaf)
storePassword=$storePassword
keyAlias=$alias
keyPassword=$keyPassword
"@

Set-Content -Path $keyPropsPath -Value $propsContent -NoNewline

# 7. 备份到 $HOME
Write-Host ""
Write-Host "[3/3] 备份 keystore + key.properties..." -ForegroundColor Green
$backupDir = Join-Path $env:USERPROFILE '.chroniccare-keystore-backup'
if (-not (Test-Path $backupDir)) {
    New-Item -ItemType Directory -Path $backupDir -Force | Out-Null
}
$date = Get-Date -Format 'yyyyMMdd-HHmmss'
$backupJks = Join-Path $backupDir "chroniccare-release-$date.jks"
$backupProps = Join-Path $backupDir "key-properties-$date.txt"
Copy-Item $keystorePath $backupJks -Force
Copy-Item $keyPropsPath $backupProps -Force
Write-Host "      备份到:"
Write-Host "        $backupJks"
Write-Host "        $backupProps"
Write-Host ""
Write-Host "[OK] keystore 生成完成!" -ForegroundColor Green
Write-Host ""
Write-Host "下一步:"
Write-Host "  1. 跑 'flutter build appbundle --release' 验证签名"
Write-Host "  2. 检查 'aapt dump badging build/app/outputs/bundle/release/app-release.aab | grep package' 确认 keystore"
Write-Host "  3. Play Console → App integrity → Enable Play App Signing + 上传 .aab"
Write-Host "  4. 备份到 1Password / Bitwarden (强烈推荐, 丢 keystore = App 永久无法升级)"
Write-Host ""
